"""diagram_stack.py -- S3 (private, OAC) + CloudFront hosting for diagram-site/index.html.

See SPEC.md Section 6 ("diagram_stack.py (hosted architecture diagram)") and,
in full detail, docs/inspection-architecture-reference.md Section 6. The
page itself (diagram-site/index.html) is generated by
diagram-site/generate_diagram.py -- computed, grid-snapped SVG coordinates
rather than hand-placed numbers; re-run that script and redeploy this stack
to update the diagram after changing the architecture.

No custom domain, no WAF/signed-URL restriction (reference doc Section
6.16) -- default is the plain *.cloudfront.net URL, open behind the private
S3 + CloudFront-only access pattern. Confirm with the user before adding
either.
"""

from pathlib import Path

import aws_cdk as cdk
from aws_cdk import CfnOutput, Duration, Stack, Tags
from aws_cdk import aws_cloudfront as cloudfront
from aws_cdk import aws_cloudfront_origins as origins
from aws_cdk import aws_s3 as s3
from aws_cdk import aws_s3_deployment as s3_deploy
from cdk_nag import NagPackSuppression, NagSuppressions
from constructs import Construct

import config

DIAGRAM_SITE_DIR = Path(__file__).parent.parent / "diagram-site"


class DiagramStack(Stack):
    """Private S3 origin behind CloudFront (OAC) serving the hand-built architecture diagram."""

    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)
        Tags.of(self).add("Layer", config.Layer.DIAGRAM)

        # ------------------------------------------------------------------
        # S3 -- private origin only. Static-website-hosting feature is
        # deliberately left off: that mode serves publicly over plain HTTP
        # and doesn't support OAC at all (reference doc Section 6.15).
        # ------------------------------------------------------------------
        bucket = s3.Bucket(
            self, "DiagramBucket",
            block_public_access=s3.BlockPublicAccess.BLOCK_ALL,
            versioned=True,
            encryption=s3.BucketEncryption.S3_MANAGED,
            enforce_ssl=True,
            removal_policy=cdk.RemovalPolicy.DESTROY,
            auto_delete_objects=True,
        )

        # ------------------------------------------------------------------
        # Response headers policy -- HSTS, nosniff, DENY framing, strict
        # referrer policy, and a CSP that's actually achievable because the
        # page has zero <script> tags and no external requests of any kind
        # (reference doc Sections 6.12 / 6.15).
        # ------------------------------------------------------------------
        response_headers_policy = cloudfront.ResponseHeadersPolicy(
            self, "DiagramResponseHeadersPolicy",
            response_headers_policy_name=f"lattice-lab-diagram-{self.region}",
            security_headers_behavior=cloudfront.ResponseSecurityHeadersBehavior(
                content_security_policy=cloudfront.ResponseHeadersContentSecurityPolicy(
                    content_security_policy=(
                        "default-src 'none'; style-src 'unsafe-inline'; "
                        "script-src 'none'; img-src 'self' data:; base-uri 'none'"
                    ),
                    override=True,
                ),
                content_type_options=cloudfront.ResponseHeadersContentTypeOptions(override=True),
                frame_options=cloudfront.ResponseHeadersFrameOptions(
                    frame_option=cloudfront.HeadersFrameOption.DENY, override=True
                ),
                referrer_policy=cloudfront.ResponseHeadersReferrerPolicy(
                    referrer_policy=cloudfront.HeadersReferrerPolicy.STRICT_ORIGIN_WHEN_CROSS_ORIGIN, override=True
                ),
                strict_transport_security=cloudfront.ResponseHeadersStrictTransportSecurity(
                    access_control_max_age=Duration.days(365), include_subdomains=True, override=True
                ),
            ),
        )

        # ------------------------------------------------------------------
        # CloudFront -- S3 origin via Origin Access Control (not legacy
        # OAI), HTTPS-only, default *.cloudfront.net certificate (no custom
        # domain -- see module docstring).
        # ------------------------------------------------------------------
        distribution = cloudfront.Distribution(
            self, "DiagramDistribution",
            default_root_object="index.html",
            minimum_protocol_version=cloudfront.SecurityPolicyProtocol.TLS_V1_2_2021,
            default_behavior=cloudfront.BehaviorOptions(
                origin=origins.S3BucketOrigin.with_origin_access_control(bucket),
                viewer_protocol_policy=cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
                allowed_methods=cloudfront.AllowedMethods.ALLOW_GET_HEAD,
                response_headers_policy=response_headers_policy,
            ),
        )

        # ------------------------------------------------------------------
        # Deploy the generated page. Cache-Control matches the reference
        # doc's "fixed key + short TTL" strategy (Section 6.15) -- this is a
        # single, occasionally-redeployed page, not a versioned asset
        # pipeline; the invalidation is what actually forces freshness.
        # ------------------------------------------------------------------
        deployment = s3_deploy.BucketDeployment(
            self, "DiagramDeployment",
            sources=[s3_deploy.Source.asset(str(DIAGRAM_SITE_DIR), exclude=["generate_diagram.py"])],
            destination_bucket=bucket,
            distribution=distribution,
            distribution_paths=["/index.html"],
            cache_control=[s3_deploy.CacheControl.from_string("public, max-age=300, must-revalidate")],
        )

        CfnOutput(self, "DiagramUrl", value=f"https://{distribution.distribution_domain_name}")

        # ------------------------------------------------------------------
        # cdk-nag suppressions (SPEC.md Section 10)
        # ------------------------------------------------------------------
        NagSuppressions.add_stack_suppressions(self, [
            NagPackSuppression(
                id="AwsSolutions-IAM4",
                reason="Managed policies here are only the framework-attached ones for "
                       "BucketDeployment's own provider Lambda, not chosen by this project's code.",
            ),
            NagPackSuppression(
                id="AwsSolutions-IAM5",
                reason="Wildcards come from CDK's BucketDeployment-generated policy (standard, not "
                       "hand-widened) for uploading the diagram page and invalidating the distribution.",
            ),
            NagPackSuppression(
                id="AwsSolutions-L1",
                reason="Flagged Lambda is BucketDeployment's own framework-managed provider function, "
                       "not project-authored code.",
            ),
            NagPackSuppression(
                id="AwsSolutions-S1",
                reason="Server access logging on the diagram bucket would need a second bucket purely "
                       "for a single static HTML page -- not worth the added infrastructure.",
            ),
            NagPackSuppression(
                id="AwsSolutions-CFR1",
                reason="Geo restriction isn't relevant to an interview-lab demo page.",
            ),
            NagPackSuppression(
                id="AwsSolutions-CFR2",
                reason="WAF is explicitly optional per docs/inspection-architecture-reference.md Section "
                       "6.16 -- default is open behind the private-origin pattern, not WAF-restricted.",
            ),
            NagPackSuppression(
                id="AwsSolutions-CFR3",
                reason="CloudFront access logging needs a dedicated log bucket -- not worth the added "
                       "infrastructure for a single lab diagram page.",
            ),
            NagPackSuppression(
                id="AwsSolutions-CFR4",
                reason="minimum_protocol_version is set to TLS_V1_2_2021 in code; this distribution uses "
                       "the default *.cloudfront.net certificate (no custom domain, per Section 6.16's "
                       "own decision), for which AWS enforces TLSv1.2+ regardless -- cdk-nag's check "
                       "appears not to recognize that default-certificate case.",
            ),
        ])
